[build]
  command = "CI='' npm run build"
  publish = "/build"
  base ="/"

  [[redirects]]
  from = "/filtercard"
  to = "/"
  status = 200

  [[redirects]]
  from = "/vendor"
  to = "/vendor"
  status = 200